/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    TheFooter: typeof import('./src/components/TheFooter.vue')['default']
    TheNavigationBar: typeof import('./src/components/TheNavigationBar.vue')['default']
  }
}
